services:
  - type: worker
    name: kuku-fm-series-bot
    runtime: docker
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: KUKU_GUEST_USER_ID
        sync: false
      - key: KUKU_JWT_TOKEN
        sync: false
